#CFLAGS=-Wall -Wno-switch-bool -Wno-unused-value -Wno-unused-but-set-variable -m68000 -nostdlib -nodefaultlibs -nostdinc -Os -ffunction-sections -fdata-sections -I../../include/

all: cursor.linux 

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $<

cursor.linux:	cursor.o
	$(CC) -o cursor.linux cursor.o

clean:
	rm -f *.o cursor
